'use client'
/**
 * @file workspace.tsx
 * @project SlothVault
 * @module Commission Workspaces
 * @description Provides developer and customer views of the entire commissioned-development relationship.
 * @logic Lead with the current stage and the next person's action, maintain independent payment and acceptance facts, and expose focused dialogs for every lifecycle operation.
 * @dependencies React Query, Ant Design, typed commission APIs, document and file interactions
 * @index_tags commissions,workspace,progress,payments,acceptance,delivery,customer
 * @author holic512
 */
import { useMemo, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, App, Button, Card, Descriptions, Empty, Grid, Input, List, Progress, Select, Space, Steps, Table, Tabs, Tag, Timeline, Typography } from 'antd'
import { ArrowLeft, ClipboardList, FileCheck2, FileSignature, FolderArchive, Plus, RefreshCw } from 'lucide-react'
import { useLocale } from 'next-intl'
import { apiFetch } from '@/lib/api-client'
import { COMMISSION_STAGES, formatFen } from '@/lib/commissions'
import type { CommissionDetail, CommissionDocumentDto } from '@/types/commissions'
import { ActionDialog } from './action-dialog'
import type { ActionDialogSpec, ActionField } from './action-dialog'
import { CommissionDraftDialog } from './draft-dialog'
import type { DraftSpec } from './draft-dialog'
import { CommissionDocumentDialog } from './document-dialog'
import { CommissionFileUpload } from './file-upload'
import { CommissionEvidencePanel } from './evidence-panel'
import styles from '@/styles/modules/commissions.module.css'

const field = (key: string, label: string, type: ActionField['type'] = 'text', required = true, initial?: unknown): ActionField => ({ key, label, type, required, initial })
const stateNames: Record<string, string> = { PENDING: '待核实', CONFIRMED: '已确认', REJECTED: '已驳回', UNPAID: '未支付', PARTIAL: '部分支付', PAID: '已付清', DRAFT: '草稿', PUBLISHED: '已发布', RECEIVED: '已接收', INCOMPLETE: '文件缺失', PROPOSED: '待评估', QUOTED: '已报价', PENDING_SIGNATURE: '待签署', OPEN: '待处理', RESOLVED: '已修复', CLOSED: '已关闭', DISPUTED: '有异议', SUBMITTED: '待确认', DEEMED: '按约记录验收', PASS: '验收通过', CONDITIONAL: '附条件通过', FAIL: '验收未通过' }
const tag = (value: string) => <Tag color={['PAID', 'CONFIRMED', 'RECEIVED', 'PASS', 'CLOSED'].includes(value) ? 'success' : ['REJECTED', 'FAIL', 'DISPUTED'].includes(value) ? 'error' : 'default'}>{stateNames[value] || value}</Tag>
function date(value: string | null) { return value ? new Date(value).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' }) : '尚未约定' }
const stageEnglish: Record<string, string> = { ASSESSMENT: 'Assessment', REQUIREMENTS: 'Requirements', CONTRACT: 'Contract signing', READY: 'Ready to start', DEVELOPMENT: 'Development', ACCEPTANCE: 'Acceptance', RECTIFICATION: 'Corrections', DELIVERY: 'Delivery', MAINTENANCE: 'Support', COMPLETED: 'Completed', PAUSED: 'Paused', TERMINATED: 'Terminated' }
export function CommissionWorkspace({ admin, id }: { admin: boolean; id?: string }) {
  const { message, modal } = App.useApp(), router = useRouter(), cache = useQueryClient(), locale = useLocale()
  const screens = Grid.useBreakpoint(), mobile = screens.md === false
  const [activeTab, setActiveTab] = useState('overview')
  const todoTab = (key: string) => key.startsWith('document-') ? 'contracts' : /^(payment|plan)-/.test(key) ? 'payments' : /^(acceptance|delivery)-/.test(key) ? 'delivery' : /^(issue|retest)-/.test(key) ? 'changes' : key === 'assessment' ? 'contracts' : 'progress'
  const en = locale.startsWith('en'), text = (zh: string, english: string) => en ? english : zh
  const prefix = admin ? '/admin/mm/commissions' : '/account/commissions', api = `/api/${admin ? 'admin' : 'account'}/commissions`, base = `${api}/${id}`
  const [keyword, setKeyword] = useState(''), [stage, setStage] = useState<string>(), [page, setPage] = useState(1), [dialog, setDialog] = useState<ActionDialogSpec | null>(null), [draft, setDraft] = useState<DraftSpec | null>(null), [viewing, setViewing] = useState<CommissionDocumentDto | null>(null)
  const list = useQuery({ queryKey: ['commissions', admin, page, keyword, stage], enabled: !id, queryFn: () => apiFetch<{ list: CommissionDetail[]; total: number }>(`${api}?${new URLSearchParams({ page: String(page), pageSize: '20', keyword, ...(stage ? { stage } : {}) })}`) })
  const detail = useQuery({ queryKey: ['commission', admin, id], enabled: Boolean(id), queryFn: () => apiFetch<CommissionDetail>(base) })
  const users = useQuery({ queryKey: ['commission-users'], enabled: admin && dialog?.action === 'create', queryFn: () => apiFetch<{ list: Array<{ id: string; username: string; displayName: string | null; role: string; status: number }> }>('/api/admin/mm/users?page=1&pageSize=100') })
  const refresh = async () => { await Promise.all([cache.invalidateQueries({ queryKey: ['commissions'] }), cache.invalidateQueries({ queryKey: ['commission'] })]) }
  const command = useMutation({ mutationFn: (payload: Record<string, unknown>) => apiFetch<CommissionDetail>(base, { method: 'POST', body: JSON.stringify({ commandId: crypto.randomUUID(), revision: detail.data!.revision, ...payload }) }), onSuccess: async () => { setDialog(null); message.success(text('记录已保存', 'Record saved')); await refresh() }, onError: (error) => message.error(error.message) })
  const create = useMutation({ mutationFn: (payload: Record<string, unknown>) => apiFetch<CommissionDetail>(api, { method: 'POST', body: JSON.stringify({ commandId: crypto.randomUUID(), ...payload }) }), onSuccess: (value) => { setDialog(null); void refresh(); router.push(`${prefix}/${value.id}`) }, onError: (error) => message.error(error.message) })
  const saveDraft = useMutation({ mutationFn: (payload: Record<string, unknown>) => apiFetch<CommissionDetail>(`${base}/documents`, { method: 'POST', body: JSON.stringify({ commandId: crypto.randomUUID(), revision: detail.data!.revision, ...payload }) }), onSuccess: async () => { setDraft(null); message.success('文件草稿已保存，请预览后正式发起'); await refresh() }, onError: (error) => message.error(error.message) })
  const openDraft = (spec: DraftSpec) => setDraft({ ...spec, commandId: crypto.randomUUID() })
  const documentAction = useMutation({ mutationFn: ({ documentId, action, reason }: { documentId: string; action: string; reason?: string }) => apiFetch(`/api/${admin ? 'admin' : 'account'}/contracts/${documentId}/${action}`, { method: 'POST', body: JSON.stringify({ reason }) }), onSuccess: async () => { setViewing(null); message.success('文件处理结果已保存'); await refresh() }, onError: (error) => message.error(error.message) })
  const open = (title: string, action: string, fields: ActionField[], fixed?: Record<string, unknown>, initial?: Record<string, unknown>) => setDialog({ title, action, fields, fixed, initial, commandId: crypto.randomUUID() })
  const effectiveDialog = useMemo(() => dialog ? { ...dialog, fields: dialog.action === 'create' && admin ? dialog.fields.map((f) => f.key === 'subjectUserId' ? { ...f, options: users.data?.list.filter((u) => u.role === 'USER' && u.status === 1).map((u) => ({ value: u.id, label: `${u.displayName || u.username}（${u.username}）` })) || [] } : f) : dialog.fields } : null, [dialog, admin, users.data])
  const d = detail.data, busy = command.isPending || create.isPending
  const submit = (values: Record<string, unknown>) => {
    const { action, ...payload } = values
    if (action === 'create') { create.mutate(payload); return }
    if (action === 'parties') {
      const partyA = Object.fromEntries(Object.entries(payload).filter(([key]) => key.startsWith('partyA')).map(([key, value]) => [key.slice(6), value]))
      const partyB = Object.fromEntries(Object.entries(payload).filter(([key]) => key.startsWith('partyB')).map(([key, value]) => [key.slice(6), value]))
      command.mutate({ action: 'update', commandId: payload.commandId, partyA, ...(admin ? { partyB } : {}) }); return
    }
    if (action === 'delivery.create' || action === 'delivery.update') {
      const items = ((payload.fileIds || []) as string[]).map((fileId) => ({ fileId: Number(fileId), label: d!.files.find((f) => f.id === String(fileId))!.originalName, versionNote: String(payload.version) }))
      const links = String(payload.links || '').split('\n').filter((line) => line.trim()).map((line) => { const [label, url, versionNote] = line.split('|').map((part) => part.trim()); return { label, url, versionNote: versionNote || '' } })
      const { fileIds: _files, links: _links, ...rest } = payload; void _files; void _links
      command.mutate({ action, ...rest, items: [...items, ...links] }); return
    }
    command.mutate({ action, ...payload })
  }
  const fileOptions = d?.files.map((f) => ({ value: f.id, label: f.originalName })) || []
  const deliveryOptions = d?.deliveries.filter((v) => v.publishedAt).map((v) => ({ value: v.id, label: v.version })) || []
  const newIssue = () => open('反馈问题或申请售后', 'issue.create', [field('title', '问题标题'), { ...field('deliveryId', '对应成果版本', 'select', false), options: deliveryOptions }, { ...field('kind', '问题类型', 'select', true, 'BUG'), options: [{ value: 'BUG', label: '原范围内的程序缺陷' }, { value: 'ADJUSTMENT', label: '原范围内的小幅调整' }, { value: 'NEW_WORK', label: '新增需求' }] }, { ...field('severity', '影响程度', 'select', true, 'GENERAL'), options: [{ value: 'SEVERE', label: '严重：核心流程无法完成' }, { value: 'GENERAL', label: '一般：影响使用但不阻断核心流程' }, { value: 'MINOR', label: '轻微：文字、样式或细节问题' }] }, field('steps', '复现步骤', 'textarea'), field('expected', '预期结果', 'textarea'), field('actual', '实际结果', 'textarea'), { ...field('fileIds', '截图或错误资料', 'multi', false, []), options: fileOptions }])
  const parties = () => {
    const labels: Record<string, string> = { Name: '真实姓名或单位名称', Identity: '身份证或统一社会信用代码', Phone: '联系电话', Email: '邮箱', Wechat: '微信', Address: '联系地址' }
    open('填写双方合同主体资料', 'parties', [false, ...(admin ? [true] : [])].flatMap((provider) => Object.entries(labels).map(([key, label]) => field(`${provider ? 'partyB' : 'partyA'}${key}`, `${provider ? '乙方' : '甲方'}${label}`, 'text', key === 'Name', (provider ? d?.partyB : d?.partyA)?.[key] || ''))))
  }
  const timeline = d ? <>
    <Button onClick={() => open('补充沟通记录', 'comment', [field('note', '沟通内容或确认事项', 'textarea')])}>添加沟通记录</Button>
    <Timeline items={d.events.map((event) => ({ title: date(event.createdAt), content: <div><strong>{event.actor}</strong><p>{event.note}</p>{event.data.reason ? <p>调整原因：{String(event.data.reason)}</p> : null}</div> }))} />
  </> : null
  const overview = d ? <div className={styles.overview}>
    <section className={styles['next-actions']}><h2>{text('下一步', 'Next actions')}</h2>{d.todos.length ? <List dataSource={d.todos.filter((todo) => todo.audience === 'BOTH' || todo.audience === (admin ? 'ADMIN' : 'USER'))} locale={{ emptyText: '目前等待对方处理，您可以查看进度和补充资料' }} renderItem={(todo) => <List.Item actions={[<Button key="process" onClick={() => setActiveTab(todoTab(todo.key))}>处理事项</Button>]}><div><strong>{todo.text}</strong>{todo.dueAt ? <p>记录期限：{date(todo.dueAt)}</p> : null}</div></List.Item>} /> : <p>当前没有待确认事项，可在时间线中联系对方。</p>}</section>
    <section><h2>合作安排</h2><Descriptions column={1} items={[{ key: 'purpose', label: '项目用途', children: d.purpose }, { key: 'quote', label: '当前报价', children: d.quotationFen ? `¥${formatFen(d.quotationFen)}` : '等待开发方评估' }, { key: 'amount', label: '生效合同金额', children: d.totalFen ? `¥${formatFen(d.totalFen)}` : '待双方签约' }, { key: 'due', label: '预计交付', children: date(d.expectedDeliveryAt) }, { key: 'adjust', label: '免费调整期限', children: d.adjustmentUntil ? date(d.adjustmentUntil) : '实际验收后计算' }, { key: 'maintenance', label: '免费维护期限', children: d.maintenanceUntil ? date(d.maintenanceUntil) : '实际验收后计算' }]} />
      <Space wrap><Button onClick={parties}>填写合同主体资料</Button><Button onClick={newIssue}>反馈问题或申请售后</Button><Button href={`${base}/archive`} icon={<FolderArchive size={15} />}>下载项目归档</Button></Space>
    </section>
    {d.warnings.map((warning) => <Alert key={warning} type="warning" showIcon title={warning} />)}
  </div> : null
  const contracts = d ? <Space orientation="vertical" style={{ width: '100%' }}>
    <Typography.Title level={4}>项目需求</Typography.Title><Typography.Paragraph style={{ whiteSpace: 'pre-wrap' }}>{d.requirements}</Typography.Paragraph>
    <Space wrap><Button onClick={() => open('修改需求说明', 'update', [field('title', '项目名称', 'text', true, d.title), field('purpose', '项目用途', 'textarea', true, d.purpose), field('requirements', '需求说明', 'textarea', true, d.requirements), ...(admin && d.agreementFen === null ? [field('quotationFen', '开发报价', 'money', false, d.quotationFen || undefined)] : [])])}>补充需求{admin ? '与报价' : ''}</Button><Button onClick={parties}>合同主体资料</Button>{admin ? <Button type="primary" icon={<FileSignature size={15} />} onClick={() => openDraft({ kind: 'AGREEMENT' })}>按模板生成正文与附件一</Button> : null}</Space>
    <List dataSource={d.documents} locale={{ emptyText: '需求与报价确定后，开发方将按模板生成正式文件' }} renderItem={(document) => <List.Item actions={[<Button key="read" onClick={() => setViewing(document)}>阅读与确认</Button>, ...(admin && document.status === 0 ? [<Button key="edit" onClick={() => openDraft({ kind: document.documentType, sourceId: document.sourceRecordId || undefined, document })}>编辑填写内容</Button>] : [])]}><List.Item.Meta title={document.title} description={`${({ 0: '草稿', 1: '待客户签署', 2: '双方已确认', '-1': '客户拒绝', '-2': '已取消' } as Record<number, string>)[document.status]}${document.signedAt ? ` · ${date(document.signedAt)}` : ''}`} /></List.Item>} />
    {admin ? <CommissionEvidencePanel documents={d.documents} onUpdated={() => void refresh()} /> : null}
  </Space> : null
  const finances = d ? <>
    <Alert type="info" showIcon title="凭证提交、到账确认和项目阶段分别记录" description="客户提交凭证后等待开发方核实。付款进度不自动修改项目阶段，开发方可按实际合作情况安排工作。" />
    {d.plans.length ? d.plans.map((plan) => <section className={styles['payment-plan']} key={plan.id}><div className={styles['section-heading']}><h3>{plan.title}</h3>{tag(plan.status)}</div><p>应付 ¥{formatFen(plan.amountFen)} · 实收 ¥{formatFen(plan.netFen)} · 待付 ¥{formatFen(plan.remainingFen)}</p><p>{plan.basis}</p>{plan.dueAt ? <p>记录付款日期：{date(plan.dueAt)}</p> : null}<Space wrap>
      {!admin ? <Button onClick={() => open('提交付款凭证', 'payment.submit', [field('amountFen', '本次付款金额', 'money'), { ...field('evidenceFileId', '选择已上传凭证', 'select'), options: d.files.filter((f) => f.purpose === 'PAYMENT').map((f) => ({ value: f.id, label: f.originalName })) }, field('note', '付款时间、平台及备注', 'textarea')], { planId: Number(plan.id) })}>提交已付款凭证</Button> : <><Button onClick={() => open('记录实际线下收款或退款', 'payment.record', [{ ...field('kind', '记录类型', 'select', true, 'RECEIPT'), options: [{ value: 'RECEIPT', label: '实际到账' }, { value: 'REFUND', label: '实际退款' }] }, field('amountFen', '金额', 'money'), field('note', '实际发生时间、依据与说明', 'textarea'), { ...field('evidenceFileId', '凭证文件（可选）', 'select', false), options: fileOptions }], { planId: Number(plan.id) })}>记录收款或退款</Button><Button onClick={() => open('付款日期与成果依据', 'payment.schedule', [field('dueAt', '付款日期', 'date', false), field('basis', '可核实的阶段成果及付款依据', 'textarea', true, plan.basis)], { planId: Number(plan.id) })}>安排付款日期</Button><Button onClick={() => open('发送站内付款提醒', 'payment.remind', [field('note', '提醒内容', 'textarea')], { planId: Number(plan.id) })}>记录催告与提醒</Button></>}
    </Space></section>) : <Empty description="签约完成后自动建立启动款、进度款和尾款安排" />}
    <Table dataSource={d.payments} rowKey="id" pagination={false} scroll={{ x: 620 }} columns={[{ title: '发生时间', dataIndex: 'createdAt', render: date }, { title: '类型', dataIndex: 'kind', render: (kind) => kind === 'REFUND' ? '退款' : '收款' }, { title: '金额', dataIndex: 'amountFen', render: (v) => `¥${formatFen(v)}` }, { title: '状态', dataIndex: 'status', render: tag }, { title: '说明与凭证', render: (_, p) => <>{p.note}{p.evidenceFileId ? <a href={`${base}/files/${p.evidenceFileId}`}> 下载凭证</a> : null}</> }, { title: '核实', render: (_, p) => admin && p.status === 'PENDING' ? <Space><Button onClick={() => open('确认凭证实际到账', 'payment.review', [field('note', '核实说明', 'textarea')], { id: Number(p.id), approve: true })}>确认到账</Button><Button danger onClick={() => open('驳回凭证并说明原因', 'payment.review', [field('note', '驳回原因', 'textarea')], { id: Number(p.id), approve: false })}>驳回</Button></Space> : null }]} />
    <CommissionFileUpload base={base} admin={admin} onUploaded={() => void refresh()} />
  </> : null
  const progress = d ? <>
    <Typography.Paragraph>{d.progressNote || '开发方将在这里发布工作安排、阶段成果与进展说明。'}</Typography.Paragraph>
    {admin ? <Space wrap><Button type="primary" onClick={() => open('更新项目阶段与开发进度', 'stage', [{ ...field('stage', '项目阶段', 'select', true, d.stage), options: Object.entries(COMMISSION_STAGES).map(([value, label]) => ({ value, label })) }, field('progress', '开发进度（0—100）', 'number', true, d.progress), field('note', '本次进展与下一步安排', 'textarea', false, d.progressNote), field('reason', '跨阶段、回退、暂停或终止原因', 'textarea', false, ''), field('expectedDeliveryAt', '当前预计交付日期', 'date', false, d.expectedDeliveryAt?.slice(0, 10))])}>调整阶段与进度</Button><Button onClick={() => open('添加开发里程碑', 'milestone', [field('title', '里程碑名称'), field('description', '工作内容与可核实成果', 'textarea'), field('dueAt', '计划完成日期', 'date', false)])}>添加里程碑</Button></Space> : null}
    <List dataSource={d.milestones} locale={{ emptyText: '尚未安排开发里程碑' }} renderItem={(m) => <List.Item actions={admin ? [<Button key="edit" onClick={() => open('更新里程碑', 'milestone', [field('title', '名称', 'text', true, m.title), field('description', '工作与成果说明', 'textarea', true, m.description), field('dueAt', '计划完成日期', 'date', false, m.dueAt?.slice(0, 10)), field('completed', '已完成', 'boolean', false, Boolean(m.completedAt))], { id: Number(m.id) })}>更新</Button>] : []}><List.Item.Meta title={<>{m.title} <Tag color={m.completedAt ? 'success' : 'processing'}>{m.completedAt ? '已完成' : '进行中'}</Tag></>} description={<>{m.description}<br />计划日期：{date(m.dueAt)}</>} /></List.Item>} />
  </> : null
  const changes = d ? <Space orientation="vertical" style={{ width: '100%' }}>
    <Space wrap><Button onClick={() => open('提出需求变更', 'change.create', [field('title', '变更名称'), field('original', '原需求内容', 'textarea'), field('proposed', '拟变更内容', 'textarea'), field('reason', '变更原因', 'textarea')])}>提出需求变更</Button><Button onClick={newIssue}>反馈问题或调整</Button></Space>
    <List header="需求变更" dataSource={d.changes} locale={{ emptyText: '暂无需求变更' }} renderItem={(c) => <List.Item actions={admin && ['PROPOSED', 'QUOTED', 'REJECTED'].includes(c.status) ? [<Button key="quote" onClick={() => open('评估变更费用与工期', 'change.quote', [field('feeFen', '新增费用', 'money', true, c.feeFen), field('extensionDays', '增加工期（天）', 'number', true, c.extensionDays), field('impact', '对其他模块的影响', 'textarea', true, c.impact)], { id: Number(c.id) })}>评估报价</Button>, ...(c.status === 'QUOTED' ? [<Button key="document" onClick={() => openDraft({ kind: 'CHANGE', sourceId: c.id })}>生成附件二</Button>] : [])] : []}><List.Item.Meta title={<>{c.title} {tag(c.status)}</>} description={<><p>原需求：{c.original}</p><p>拟变更：{c.proposed}</p><p>原因：{c.reason}</p><p>新增 ¥{formatFen(c.feeFen)}，增加 {c.extensionDays} 天；{c.impact || '等待开发方评估'}</p></>} /></List.Item>} />
    <List header="问题、修复与售后" dataSource={d.issues} locale={{ emptyText: '暂无问题反馈' }} renderItem={(i) => <List.Item actions={[<Button key="update" onClick={() => open(admin ? '处理问题与分类' : '确认修复或提出异议', 'issue.update', [{ ...field('status', '处理结果', 'select', true, admin ? 'RESOLVED' : 'CLOSED'), options: (admin ? ['OPEN', 'RESOLVED', 'CLOSED', 'DISPUTED'] : ['CLOSED', 'DISPUTED', 'OPEN']).map((value) => ({ value, label: stateNames[value] })) }, field('resolution', admin ? '修复、分类依据与后续安排' : '复测结果或具体异议', 'textarea'), ...(admin ? [{ ...field('kind', '问题分类', 'select', false, i.kind), options: [{ value: 'BUG', label: '原范围缺陷，免费修复' }, { value: 'ADJUSTMENT', label: '小幅调整' }, { value: 'NEW_WORK', label: '新增需求，需要变更确认' }] }, field('dueAt', '计划处理日期', 'date', false)] : [])], { id: Number(i.id) })}>{admin ? '处理' : '反馈复测结果'}</Button>]}><List.Item.Meta title={<>{i.title} {tag(i.status)} <Tag color={i.severity === 'SEVERE' ? 'error' : 'default'}>{({ SEVERE: '严重', GENERAL: '一般', MINOR: '轻微' } as Record<string, string>)[i.severity]}</Tag></>} description={<><p>复现：{i.steps}</p><p>预期：{i.expected}</p><p>实际：{i.actual}</p>{i.resolution ? <p>处理：{i.resolution}</p> : null}{i.fileIds.map((fileId) => <a key={fileId} href={`${base}/files/${fileId}`}>问题资料 {fileId} </a>)}</>} /></List.Item>} />
  </Space> : null
  const deliveries = d ? <Space orientation="vertical" style={{ width: '100%' }}>
    {admin ? <Button type="primary" onClick={() => open('建立成果交付批次', 'delivery.create', [field('version', '交付版本'), { ...field('kind', '成果用途', 'select', true, 'FINAL'), options: [{ value: 'DEMO', label: '阶段演示或测试成果' }, { value: 'FINAL', label: '完整交付成果' }] }, field('note', '交付说明', 'textarea', false, ''), field('testInstructions', '测试方法、运行环境与必要说明', 'textarea', true, ''), { ...field('fileIds', '选择系统文件', 'multi', false, []), options: fileOptions }, field('links', '补充链接（每行：标题 | 地址 | 版本或提交号）', 'textarea', false, '')])}>建立交付批次</Button> : null}
    {d.deliveries.map((delivery) => <section key={delivery.id} className={styles['delivery-batch']}><div className={styles['section-heading']}><h3>{delivery.version} <Tag>{delivery.kind === 'DEMO' ? '阶段成果' : '完整交付'}</Tag></h3>{tag(delivery.status)}</div><p>{delivery.note}</p><p>测试说明：{delivery.testInstructions}</p><List dataSource={delivery.items} renderItem={(item) => <List.Item><div>{item.fileId ? <a href={`${base}/files/${item.fileId}`}>{item.label}</a> : <a href={item.url || undefined} target="_blank" rel="noreferrer noopener">{item.label} <Tag>外部资源</Tag></a>}<p>{item.versionNote}</p></div></List.Item>} /><Space wrap>
      {admin && delivery.status === 'DRAFT' ? <Button onClick={() => open('编辑未发布交付批次', 'delivery.update', [field('version', '交付版本', 'text', true, delivery.version), { ...field('kind', '成果用途', 'select', true, delivery.kind), options: [{ value: 'DEMO', label: '阶段成果' }, { value: 'FINAL', label: '完整交付' }] }, field('note', '说明', 'textarea', false, delivery.note), field('testInstructions', '测试与运行说明', 'textarea', true, delivery.testInstructions), { ...field('fileIds', '系统文件', 'multi', false, delivery.items.flatMap((i) => i.fileId ? [i.fileId] : [])), options: fileOptions }, field('links', '外部链接（标题 | 地址 | 版本）', 'textarea', false, delivery.items.filter((i) => i.url).map((i) => `${i.label} | ${i.url} | ${i.versionNote}`).join('\n'))], { id: Number(delivery.id) })}>编辑草稿</Button> : null}
      {admin && delivery.status === 'DRAFT' ? <Button type="primary" onClick={() => modal.confirm({ title: '发布此批次并向客户开放文件', content: '发布后清单冻结，更新成果时请建立新批次。请核对版本、文件及实际付款安排。', onOk: () => command.mutateAsync({ action: 'delivery.publish', id: Number(delivery.id) }) })}>正式发布交付</Button> : null}
      {delivery.publishedAt ? <><Button href={`${base}/archive?deliveryId=${delivery.id}`}>下载本批次 ZIP</Button>{!admin ? <><Button onClick={() => open('确认交付资料已接收', 'delivery.receive', [field('note', '接收说明', 'textarea', false, '')], { id: Number(delivery.id), received: true })}>确认接收文件</Button><Button onClick={() => open('反馈交付资料缺失', 'delivery.receive', [field('note', '缺失资料及具体问题', 'textarea')], { id: Number(delivery.id), received: false })}>反馈缺失</Button></> : null}<Button icon={<FileCheck2 size={15} />} onClick={() => open('记录本轮功能验收结果', 'acceptance.create', [{ ...field('result', '验收结果', 'select', true, 'PASS'), options: ['PASS', 'CONDITIONAL', 'FAIL'].map((value) => ({ value, label: stateNames[value] })) }, field('basis', '验收依据与测试范围', 'textarea'), field('outstanding', '遗留问题、修复期限或整改要求', 'textarea', false, '')], { deliveryId: Number(delivery.id) })}>记录验收结果</Button></> : null}
    </Space>{delivery.receiptNote ? <p>客户接收反馈：{delivery.receiptNote}</p> : null}</section>)}
    <List header="验收记录" dataSource={d.acceptances} locale={{ emptyText: '完整可测试成果发布后，双方在这里记录验收与复验' }} renderItem={(a) => <List.Item actions={admin ? [ ...(a.status === 'DRAFT' ? [<Button key="doc" onClick={() => openDraft({ kind: 'ACCEPTANCE', sourceId: a.id })}>生成附件三</Button>] : []), ...(a.status === 'SUBMITTED' ? [<Button key="remind" onClick={() => open('验收补充提醒', 'acceptance.remind', [field('note', '提醒内容、已提供的成果及测试说明', 'textarea')], { id: Number(a.id) })}>补充提醒</Button>, <Button key="deem" onClick={() => open('依据第 7.8 条记录视为验收', 'acceptance.deem', [field('basis', '核对通知、期限、异议及无正当理由未反馈的具体依据（不少于20字）', 'textarea')], { id: Number(a.id) })}>记录期限验收依据</Button>] : []) ] : []}><List.Item.Meta title={<>{tag(a.result)}{tag(a.status)}</>} description={<><p>{a.basis}</p><p>{a.outstanding}</p>{a.supplementalDueAt ? <p>补充反馈期限：{date(a.supplementalDueAt)}</p> : null}{a.deemedBasis ? <p>开发方按约记录依据：{a.deemedBasis}；此记录没有生成客户签名。</p> : null}</>} /></List.Item>} />
  </Space> : null
  const aftercare = d ? <Space orientation="vertical" style={{ width: '100%' }}><Alert showIcon type="info" title="合作结束后，约定的维护责任继续履行" description={`免费调整期：${date(d.adjustmentUntil)}；免费缺陷维护期：${date(d.maintenanceUntil)}。原范围缺陷、小幅调整和新增需求分别记录，收费新增内容通过变更确认。`} /><Descriptions column={1} items={[{ key: 'allowance', label: '约定免费调整次数', children: d.aftercare.adjustmentRounds === null ? '按正式合同填写内容核对' : `${d.aftercare.adjustmentRounds} 次` }, { key: 'workload', label: '约定调整工作量', children: d.aftercare.adjustmentWorkload || '以合同范围及次数为准' }, { key: 'channel', label: '售后联系渠道', children: d.aftercare.supportChannel || '可在项目时间线留言' }]} /><Button onClick={newIssue}>提交售后问题或调整请求</Button><List dataSource={d.issues.filter((i) => i.kind === 'BUG' || i.kind === 'ADJUSTMENT' || i.kind === 'NEW_WORK')} locale={{ emptyText: '当前暂无售后事项' }} renderItem={(i) => <List.Item><List.Item.Meta title={<>{i.title} {tag(i.status)}</>} description={`${i.kind === 'BUG' ? '缺陷修复' : i.kind === 'ADJUSTMENT' ? '范围内调整，需核对期限与次数' : '新增工作，需确认费用与工期'}；${i.resolution || '等待处理'}；计划日期：${date(i.dueAt)}`} /></List.Item>} /><Descriptions title="暂停或解除后的结算记录" column={1} items={Object.entries(d.settlement).map(([key, value]) => ({ key, label: ({ completedWork: '已完成工作', payableFen: '尚应支付', refundableFen: '应退金额', intellectualProperty: '成果与知识产权处理', resources: '资料与权限处理', note: '补充说明' } as Record<string, string>)[key] || key, children: key.endsWith('Fen') ? `¥${formatFen(String(value))}` : String(value) }))} />{admin ? <Button onClick={() => open('记录暂停或解除结算', 'settlement', [field('completedWork', '已完成工作', 'textarea'), field('payableFen', '尚应支付金额', 'money'), field('refundableFen', '应退金额', 'money'), field('intellectualProperty', '成果与知识产权处理', 'textarea'), field('resources', '资料与权限处理', 'textarea'), field('note', '补充说明', 'textarea', false, '')])}>填写结算安排</Button> : null}</Space> : null
  const files = d ? <>
    <CommissionFileUpload base={base} admin={admin} onUploaded={() => void refresh()} />
    <Table rowKey="id" dataSource={d.files} pagination={false} scroll={{ x: 640 }} columns={[{ title: '文件', render: (_, f) => <a href={`${base}/files/${f.id}`}>{f.originalName}</a> }, { title: '用途', dataIndex: 'purpose', render: (v) => ({ REQUIREMENT: '需求资料', PAYMENT: '付款凭证', TEST: '测试资料', DELIVERY: '交付成果' } as Record<string, string>)[v] }, { title: '大小', dataIndex: 'fileSize', render: (v) => `${(Number(v) / 1024 / 1024).toFixed(2)} MiB` }, { title: '上传时间', dataIndex: 'createdAt', render: date }, { title: '校验', render: (_, f) => <details><summary>SHA-256</summary><Typography.Text copyable>{f.sha256}</Typography.Text></details> }]} />
  </> : null
  return <div className={styles.workspace}>
    <div className={styles.heading}><div>{id ? <Link href={prefix}><ArrowLeft size={15} />{text('返回委托项目', 'Back to commissions')}</Link> : null}<h1>{id ? d?.title || text('正在加载项目', 'Loading project') : text(admin ? '委托项目管理' : '我的委托项目', admin ? 'Commission management' : 'My commissions')}</h1><p>{id ? d?.commissionId : text('需求、合同、付款、进度、验收与交付，都在同一个项目里', 'Requirements, contracts, payments, progress and delivery in one workspace')}</p></div><Space wrap><Button icon={<RefreshCw size={15} />} onClick={() => void refresh()}>{text('刷新', 'Refresh')}</Button>{!id ? <Button type="primary" icon={<Plus size={15} />} onClick={() => open(admin ? '建立客户委托项目' : '提交委托需求', 'create', [...(admin ? [{ ...field('subjectUserId', '客户账户', 'select'), options: users.data?.list.filter((u) => u.role === 'USER' && u.status === 1).map((u) => ({ value: u.id, label: `${u.displayName || u.username}（${u.username}）` })) || [] }] : []), field('title', '项目名称'), field('purpose', '项目用途', 'textarea'), field('requirements', '需求说明、预期交付及时间安排', 'textarea')])}>{text(admin ? '建立委托' : '提交委托需求', admin ? 'Create commission' : 'Submit requirements')}</Button> : null}</Space></div>
    {(id ? detail : list).isError ? <Alert type="error" showIcon title="加载失败" description={String((id ? detail : list).error)} action={<Button onClick={() => void refresh()}>重试</Button>} /> : null}
    {!id ? <><div className={styles.filters}><Input.Search allowClear placeholder={text('搜索项目名称', 'Search project name')} value={keyword} onChange={(e) => { setKeyword(e.target.value); setPage(1) }} /><Select allowClear placeholder={text('全部阶段', 'All stages')} value={stage} options={Object.entries(COMMISSION_STAGES).map(([value, label]) => ({ value, label: en ? stageEnglish[value] : label }))} onChange={(value) => { setStage(value); setPage(1) }} /></div>
      <Card>{mobile ? <List loading={list.isPending} dataSource={list.data?.list || []} pagination={{ current: page, total: list.data?.total, pageSize: 20, onChange: setPage, simple: true }} locale={{ emptyText: <Empty description={text(admin ? '建立首个委托项目' : '提交需求，开始合作', 'Start your first commission')} /> }} renderItem={(item) => <List.Item className={styles['mobile-project']}><Link href={`${prefix}/${item.id}`}><h3>{item.title}</h3></Link><p>{item.todos.find((todo) => todo.audience === (admin ? 'ADMIN' : 'USER'))?.text || '等待对方处理'}</p><Space wrap><Tag>{en ? stageEnglish[item.stage] : COMMISSION_STAGES[item.stage]}</Tag><Tag>{item.paymentSummary}</Tag></Space><Progress percent={item.progress} size="small" /><Button href={`${prefix}/${item.id}`}>{text('查看项目与处理待办', 'View project and next actions')}</Button></List.Item>} /> : <Table rowKey="id" loading={list.isPending} dataSource={list.data?.list || []} scroll={{ x: 840 }} locale={{ emptyText: <Empty description={text(admin ? '建立首个委托，邀请客户参与完整合作流程' : '提交需求，开始与开发方沟通项目安排', 'Create a commission to begin the collaboration')} /> }} pagination={{ current: page, total: list.data?.total, pageSize: 20, onChange: setPage }} columns={[{ title: text('委托项目', 'Commission'), render: (_, item) => <Link href={`${prefix}/${item.id}`}><strong>{item.title}</strong><br /><Typography.Text type="secondary">{item.subject.displayName || item.subject.username}</Typography.Text></Link> }, { title: text('当前阶段', 'Stage'), render: (_, item) => <Tag>{en ? stageEnglish[item.stage] : COMMISSION_STAGES[item.stage]}</Tag> }, { title: text('开发进度', 'Progress'), render: (_, item) => <Progress percent={item.progress} size="small" /> }, { title: text('付款情况', 'Payments'), dataIndex: 'paymentSummary' }, { title: text('下一步', 'Next action'), render: (_, item) => item.todos.find((todo) => todo.audience === (admin ? 'ADMIN' : 'USER'))?.text || '等待对方处理' }, { title: text('预计交付', 'Expected delivery'), dataIndex: 'expectedDeliveryAt', render: date }]} />}</Card>
    </> : d ? <><div className={styles['status-band']}><div><Tag color="processing">{en ? stageEnglish[d.stage] : COMMISSION_STAGES[d.stage]}</Tag><Tag>{d.paymentSummary}</Tag><Tag>{d.documents.some((doc) => doc.documentType === 'AGREEMENT' && doc.status === 2) ? '正文及附件一已签署' : d.documents.some((doc) => doc.status === 1) ? '文件待客户确认' : '合同待确认'}</Tag>{d.acceptances[0] ? <Tag>{stateNames[d.acceptances[0].result]} · {stateNames[d.acceptances[0].status] || d.acceptances[0].status}</Tag> : <Tag>尚未完成验收</Tag>}<Tag>{d.deliveries.some((v) => v.status === 'RECEIVED' && v.kind === 'FINAL') ? '交付文件已接收' : d.deliveries.some((v) => v.publishedAt && v.kind === 'FINAL') ? '成果已交付，待接收' : '完整成果待交付'}</Tag><p>{d.progressNote || text('这里将显示开发方最新的进展说明', 'The latest development update appears here')}</p></div><div className={styles['progress-meter']}><span>{text('开发方填报进度', 'Reported development progress')}</span><Progress percent={d.progress} /></div></div>
      {!mobile ? <div className={styles['stage-navigation']}><Steps size="small" current={Object.keys(COMMISSION_STAGES).slice(0, 10).indexOf(d.stage)} items={Object.entries(COMMISSION_STAGES).slice(0, 10).map(([key, title]) => ({ title: en ? stageEnglish[key] : title }))} /></div> : null}
      <Tabs activeKey={activeTab} onChange={setActiveTab} items={[{ key: 'overview', label: text('概览与待办', 'Overview'), icon: <ClipboardList size={15} />, children: overview }, { key: 'contracts', label: text('需求与合同', 'Requirements and documents'), children: contracts }, { key: 'payments', label: text('付款', 'Payments'), children: finances }, { key: 'progress', label: text('开发进度', 'Progress'), children: progress }, { key: 'changes', label: text('变更与问题', 'Changes and issues'), children: changes }, { key: 'delivery', label: text('验收与交付', 'Acceptance and delivery'), children: deliveries }, { key: 'aftercare', label: text('售后与结算', 'Support and settlement'), children: aftercare }, { key: 'files', label: text('项目文件', 'Files'), children: files }, { key: 'timeline', label: text('沟通与时间线', 'Timeline'), children: timeline }]} />
      <CommissionDraftDialog key={draft?.commandId || 'closed'} spec={draft} detail={d} busy={saveDraft.isPending} onClose={() => setDraft(null)} onSave={(payload) => saveDraft.mutate(payload)} />
      <CommissionDocumentDialog key={viewing?.id || 'closed'} commissionBase={base} document={viewing} admin={admin} busy={documentAction.isPending} onClose={() => setViewing(null)} onAction={(documentId, action, reason) => { if (action === 'cancel') modal.confirm({ title: '取消此正式文件', content: '取消后保留原文件及操作记录，若需继续合作应重新生成。', okButtonProps: { danger: true }, onOk: () => documentAction.mutateAsync({ documentId, action }) }); else documentAction.mutate({ documentId, action, reason }) }} />
    </> : <Card loading />}
    <ActionDialog spec={effectiveDialog} busy={busy} onClose={() => setDialog(null)} onSave={submit} />
  </div>
}
