'use client'
/**
 * @file workspace.tsx
 * @project SlothVault
 * @module Commission Workspace
 * @description Presents one timeline-led workflow to administrators and customers.
 * @logic Separate lifecycle, payment and maintenance while offering stage-specific commands and immutable submissions.
 * @dependencies React Query, Ant Design, commission workflow APIs
 * @index_tags commissions,workspace,timeline,contracts
 * @author holic512
 */
import { useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, App, Button, Descriptions, Drawer, Empty, Form, Input, Modal, Progress, Select, Space, Spin, Table, Tabs, Tag, Timeline } from 'antd'
import { apiFetch } from '@/lib/api-client'
import { WORKFLOW_STAGES, type WorkflowAgreement, type WorkflowDetail, type WorkflowSummary } from '@/lib/commission-workflow'
import { MarkdownView } from '@/components/markdown/markdown-view'
import { formatFen } from '@/lib/commissions'
import { ActionDialog, type ActionDialogSpec, type ActionField } from './action-dialog'
import { CommissionFileUpload } from './file-upload'
import { WorkflowAgreementEditor } from './workflow-agreement-editor'
import { WorkflowEvidencePanel } from './workflow-evidence-panel'
import styles from '@/styles/modules/commission-workflow.module.css'
const date = (value: string | null) => value ? new Date(value).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' }) : '尚未开始'
const eventNames: Record<string, string> = { 'request.submit': '提交委托', 'request.accept': '管理员接单', 'request.return': '退回补充', 'invitation.claim': '用户认领', 'submission.create': '补充记录', 'agreement.publish': '发布合同', 'agreement.confirm': '在线确认合同', 'agreement.offline': '记录线下确认', 'agreement.decline': '合同异议', 'payment.update': '更新用户支付比例', 'project.start': '开始实施', 'project.pause': '调整暂停状态', 'project.terminate': '终止委托', 'delivery.publish': '正式交付，开始维护', 'issue.create': '维护问题', 'issue.update': '问题处理', 'maintenance.close': '关闭维护' }
const kinds: Record<string, string> = { REQUIREMENT: '补充需求', COMMENT: '沟通记录', PROGRESS: '实施进展', DEMO: '阶段成果', REPAIR: '修复交付' }
const contractStates: Record<string, string> = { DRAFT: '草稿', PENDING: '待确认', CONFIRMED: '已确认', DECLINED: '有异议', SUPERSEDED: '已被新版本替代' }
const noteField: ActionField = { key: 'note', label: '说明', type: 'textarea', required: true }
export function CommissionWorkspace({ admin, id }: { admin: boolean; id?: string }) {
  const router = useRouter(), cache = useQueryClient(), { message, modal } = App.useApp()
  const api = `/api/${admin ? 'admin' : 'account'}/commissions`, prefix = admin ? '/admin/mm/commissions' : '/account/commissions', base = `${api}/${id}`
  const [keyword, setKeyword] = useState(''), [stage, setStage] = useState<string>(), [page, setPage] = useState(1), [tab, setTab] = useState('timeline')
  const [dialog, setDialog] = useState<ActionDialogSpec | null>(null), [createOpen, setCreateOpen] = useState(false), [createForm] = Form.useForm()
  const [userSearch, setUserSearch] = useState(''), [invite, setInvite] = useState<{ path: string; expiresAt: string } | null>(null)
  const [draft, setDraft] = useState<{ agreement?: WorkflowAgreement; kind: string; commandId: string } | null>(null), [reading, setReading] = useState<WorkflowAgreement | null>(null)
  const entry = Form.useWatch('entry', createForm)
  const list = useQuery({ queryKey: ['workflow-list', admin, page, keyword, stage], enabled: !id, queryFn: () => apiFetch<{ list: WorkflowSummary[]; total: number }>(`${api}?${new URLSearchParams({ page: String(page), pageSize: '20', keyword, ...(stage ? { stage } : {}) })}`) })
  const query = useQuery({ queryKey: ['workflow', admin, id], enabled: Boolean(id), queryFn: () => apiFetch<WorkflowDetail>(base), refetchInterval: 30000 })
  const users = useQuery({ queryKey: ['workflow-users', userSearch], enabled: admin && createOpen && entry === 'user', queryFn: () => apiFetch<{ list: Array<{ id: string; username: string; displayName: string | null; role: string; status: number }> }>(`/api/admin/mm/users?${new URLSearchParams({ page: '1', pageSize: '100', keyword: userSearch })}`) })
  const refresh = async () => { await Promise.all([cache.invalidateQueries({ queryKey: ['workflow'] }), cache.invalidateQueries({ queryKey: ['workflow-list'] })]) }
  const command = useMutation({ mutationFn: (payload: Record<string, unknown>) => apiFetch<WorkflowDetail>(base, { method: 'POST', body: JSON.stringify({ commandId: crypto.randomUUID(), revision: query.data!.revision, ...payload }) }), onSuccess: async () => { setDialog(null); setDraft(null); setReading(null); message.success('记录已保存'); await refresh() }, onError: (error) => message.error(error.message) })
  const create = useMutation({ mutationFn: (values: { title: string; requirements?: string; subjectUserId?: string; entry?: string }) => apiFetch<WorkflowDetail>(api, { method: 'POST', body: JSON.stringify({ commandId: crypto.randomUUID(), title: values.title, requirements: values.requirements || '', ...(admin && values.entry === 'user' ? { subjectUserId: Number(values.subjectUserId) } : {}), draft: true }) }), onSuccess: (row) => { setCreateOpen(false); void refresh(); router.push(`${prefix}/${row.id}`) }, onError: (error) => message.error(error.message) })
  const inviteMutation = useMutation({ mutationFn: (revoke: boolean) => apiFetch<{ path: string; expiresAt: string }>(`${base}/invitations`, { method: revoke ? 'DELETE' : 'POST', body: JSON.stringify({ revision: query.data!.revision }) }), onSuccess: (value, revoke) => { if (!revoke) setInvite(value); message.success(revoke ? '邀请已撤销' : '邀请已生成，旧链接已失效'); void refresh() }, onError: (error) => message.error(error.message) })
  const d = query.data, can = (action: string) => d?.allowedActions.includes(action)
  const filesField: ActionField = { key: 'fileKeys', label: '关联已上传附件', type: 'multi', initial: [], options: d?.files.map((file) => ({ value: file.key, label: `${file.name}${file.submitted ? '' : '（草稿）'}` })) || [] }
  const referenceField: ActionField = { key: 'reference', label: '补充或更正哪条记录（可选）', type: 'select', options: d?.events.map((event) => ({ value: event.id, label: `${eventNames[event.snapshot.type]} · ${event.snapshot.note.slice(0, 30)}` })) || [] }
  const open = (title: string, action: string, fields: ActionField[], fixed?: Record<string, unknown>) => setDialog({ title, action, fields, fixed, commandId: crypto.randomUUID() })
  const confirm = (title: string, payload: Record<string, unknown>) => modal.confirm({ title, content: '确认后将产生不可覆盖的正式时间轴记录。', okText: '确认提交', cancelText: '返回', onOk: async () => { await command.mutateAsync(payload) } })
  const supplement = (kind = 'REQUIREMENT') => open(kinds[kind], 'submission.create', [noteField, filesField, referenceField, ...(kind === 'PROGRESS' ? [{ key: 'progress', label: '实施进度（0—100）', type: 'number' as const, initial: d?.progress || 0, required: true }] : [])], { kind })
  const updatePayment = () => open('更新用户支付比例', 'payment.update', [{ key: 'percent', label: '已支付比例（0—100）', type: 'number', required: true, initial: d?.paymentPercent || 0 }, { ...noteField, required: false, label: '付款说明（调低比例时必填）' }, filesField])
  if (!id) return <div className={styles.workspace}>
    <header className={styles.heading}><div><h1>{admin ? '委托管理' : '我的委托'}</h1><p>从需求、合同到交付与维护，在同一条时间轴中跟进。</p></div><Space>{admin ? <Link href="/admin/mm/contract-templates"><Button>合同模板</Button></Link> : null}<Button type="primary" onClick={() => { createForm.resetFields(); setCreateOpen(true) }}>建立委托</Button></Space></header>
    <div className={styles.filters}><Input.Search placeholder="搜索委托名称" allowClear onSearch={(value) => { setKeyword(value); setPage(1) }} /><Select placeholder="全部阶段" allowClear value={stage} onChange={(value) => { setStage(value); setPage(1) }} options={Object.entries(WORKFLOW_STAGES).map(([value, label]) => ({ value, label }))} /><Button onClick={() => void list.refetch()}>刷新</Button></div>
    {list.error ? <Alert type="error" title={list.error.message} /> : null}
    <Table rowKey="id" dataSource={list.data?.list} loading={list.isPending} scroll={{ x: 850 }} pagination={{ current: page, total: list.data?.total, pageSize: 20, showSizeChanger: false, onChange: setPage }} locale={{ emptyText: <Empty description="还没有委托，建立委托后即可准备需求与合同" /> }} columns={[
      { title: '委托', dataIndex: 'title', render: (title, row) => <Link href={`${prefix}/${row.id}`}>{title}</Link> }, { title: '关联用户', dataIndex: 'subject', render: (value) => value || '待认领' },
      { title: '当前阶段', render: (_, row) => <Tag>{row.archived ? '历史归档' : WORKFLOW_STAGES[row.stage]}{row.paused ? ' · 暂停' : ''}</Tag> },
      { title: '用户支付比例', dataIndex: 'paymentPercent', width: 150, render: (value) => <Progress percent={value} size="small" /> },
      { title: '待处理事项', dataIndex: 'nextAction' }, { title: '更新时间', dataIndex: 'updatedAt', render: date },
    ]} />
    <Modal title="建立委托" open={createOpen} onCancel={() => setCreateOpen(false)} onOk={() => createForm.submit()} confirmLoading={create.isPending} okText="建立草稿" cancelText="返回"><Form form={createForm} layout="vertical" initialValues={{ entry: 'invite' }} onFinish={(values) => create.mutate(values)}>
      <Form.Item name="title" label="委托名称" rules={[{ required: true }]}><Input maxLength={255} /></Form.Item>
      {admin ? <><Form.Item name="entry" label="参与用户"><Select options={[{ value: 'invite', label: '生成链接邀请用户认领' }, { value: 'user', label: '指定已有用户' }]} /></Form.Item>{entry === 'user' ? <Form.Item name="subjectUserId" label="选择用户" rules={[{ required: true }]}><Select showSearch filterOption={false} onSearch={setUserSearch} loading={users.isFetching} options={users.data?.list.filter((user) => user.role === 'USER' && user.status === 1).map((user) => ({ value: user.id, label: user.displayName ? `${user.displayName}（${user.username}）` : user.username }))} /></Form.Item> : null}</> : null}
      <Form.Item name="requirements" label="需求草稿"><Input.TextArea rows={5} maxLength={10000} placeholder="说明项目目标和需要实现的内容，建立后可继续上传附件。" /></Form.Item>
    </Form></Modal>
  </div>
  if (!d) return <div className={styles.workspace}>{query.error ? <Alert type="error" title={query.error.message} /> : <Spin />}</div>
  const attachmentLinks = (keys: string[]) => <Space wrap>{keys.map((key) => { const file = d.files.find((item) => item.key === key); return file ? <a key={key} href={`${base}/files/${file.id}`}>{file.name}</a> : <span key={key}>附件缺失</span> })}</Space>
  const primary = d.archived ? null : d.stage === 'DRAFT' ? <Button type="primary" onClick={() => open('正式提交委托', 'request.submit', [{ ...noteField, label: '委托需求', initial: d.requirements }, filesField])}>提交委托</Button>
    : can('request.accept') ? <Button type="primary" onClick={() => confirm('确认接受此委托', { action: 'request.accept' })}>接单</Button>
    : can('project.start') ? <Button type="primary" onClick={() => confirm('开始实施项目', { action: 'project.start' })}>开始实施</Button>
    : can('delivery.publish') ? <Button type="primary" onClick={() => open('正式交付并开始维护', 'delivery.publish', [{ ...noteField, label: '交付说明与使用方法' }, { ...filesField, required: true }, { key: 'linksText', label: '补充链接（每行一个，可选）', type: 'textarea' }])}>正式交付</Button>
    : d.stage === 'ACCEPTED' && admin ? <Button type="primary" onClick={() => setDraft({ kind: 'AGREEMENT', commandId: crypto.randomUUID() })}>生成合同</Button>
    : d.stage === 'CONTRACT_PENDING' ? <Button type="primary" onClick={() => setTab('contracts')}>查看待确认合同</Button>
    : can('issue.create') ? <Button type="primary" onClick={() => open('提交维护问题', 'issue.create', [{ key: 'title', label: '问题标题', required: true }, { ...noteField, label: '问题现象、复现步骤与预期结果' }, filesField])}>反馈维护问题</Button> : null
  const timeline = <section><div className={styles['section-heading']}><h2>委托时间轴</h2>{can('submission.create') ? <Button onClick={() => supplement('COMMENT')}>添加沟通记录</Button> : null}</div>
    {d.events.length ? <Timeline items={[...d.events].reverse().map((event) => ({ color: event.snapshot.type === 'delivery.publish' ? 'green' : 'gray', content: <article className={styles.event}>
      <div className={styles['event-heading']}><strong>{event.snapshot.type === 'submission.create' ? kinds[String(event.snapshot.data.kind)] : eventNames[event.snapshot.type] || event.snapshot.type}</strong><span>{event.snapshot.actor.name} · {date(event.snapshot.submittedAt)}</span></div><p>{event.snapshot.note}</p>
      {event.snapshot.type === 'payment.update' ? <Tag>用户支付比例 {String(event.snapshot.data.before)}% → {String(event.snapshot.data.after)}%</Tag> : null}
      {event.snapshot.reference ? <p className={styles.muted}>补充记录：{d.events.find((item) => item.id === event.snapshot.reference)?.snapshot.note.slice(0, 80)}</p> : null}
      {attachmentLinks(event.snapshot.attachments.map((file) => file.key))}
      <details className={styles['proof-details']}><summary>{event.proofs.some((proof) => proof.status === 'FINALIZED') ? '已完成链上存证' : '已冻结，链上存证待完成'}</summary><p>SHA-256：{event.hash}</p><p>前序摘要：{event.snapshot.previousHash || '首条记录'}</p>{event.proofs.map((proof) => <p key={proof.id}>{proof.network} · {proof.status}{proof.signature ? <> · <a href={`/commission-evidence/${proof.signature}`} target="_blank" rel="noreferrer">核验凭证</a></> : null}{proof.blockTime ? ` · 链上时间 ${date(proof.blockTime)}` : ''}</p>)}</details>
    </article> }))} /> : <Empty description={d.archived ? '旧流程记录请下载归档查阅' : '完善需求与附件后，提交第一条正式记录。'} />}
  </section>
  const contracts = <section><div className={styles['section-heading']}><h2>需求与合同</h2><Space wrap>{can('submission.create') ? <Button onClick={() => supplement()}>补充需求</Button> : null}{can('agreement.save') ? <Button onClick={() => setDraft({ kind: d.agreements.some((item) => item.kind === 'AGREEMENT' && item.status === 'CONFIRMED') ? 'SUPPLEMENT' : 'AGREEMENT', commandId: crypto.randomUUID() })}>生成合同或补充协议</Button> : null}</Space></div><p className={styles.prewrap}>{d.requirements}</p>
    {d.agreements.length ? d.agreements.map((agreement) => <article className={styles.record} key={agreement.id}><div className={styles['section-heading']}><h3>{agreement.title}</h3><Tag>{contractStates[agreement.status]}</Tag></div><p>{agreement.confirmationMode === 'ONLINE' ? '用户在线确认' : '管理员记录线下确认'} · 维护 {agreement.maintenanceDays} 天{agreement.totalFen ? ` · ¥${formatFen(agreement.totalFen)}` : ''}</p><Space wrap><Button onClick={() => setReading(agreement)}>阅读合同</Button>
      {admin && agreement.status === 'DRAFT' ? <><Button onClick={() => setDraft({ agreement, kind: agreement.kind, commandId: crypto.randomUUID() })}>编辑草稿</Button><Button disabled={!can('agreement.publish')} onClick={() => confirm('发布此合同版本', { action: 'agreement.publish', id: Number(agreement.id) })}>发布合同</Button></> : null}
      {admin && agreement.status === 'PENDING' && agreement.confirmationMode === 'OFFLINE' ? <Button disabled={!can('agreement.offline')} onClick={() => open('记录双方线下确认', 'agreement.offline', [noteField, { key: 'confirmedAt', label: '实际确认日期', type: 'date', required: true }, { ...filesField, label: '线下确认依据', required: true }], { id: Number(agreement.id), eventId: agreement.publishedEventId })}>记录线下确认</Button> : null}
    </Space></article>) : <Empty description="管理员接单后，选择Markdown模板生成合同" />}
  </section>
  const maintenance = <section><div className={styles['section-heading']}><h2>交付与维护</h2><Space wrap>{admin && !d.paused && ['IN_PROGRESS', 'MAINTENANCE'].includes(d.stage) ? <><Button onClick={() => supplement(d.stage === 'MAINTENANCE' ? 'REPAIR' : 'DEMO')}>{d.stage === 'MAINTENANCE' ? '补充修复交付' : '提交阶段成果'}</Button>{d.stage === 'IN_PROGRESS' ? <Button onClick={() => supplement('PROGRESS')}>更新实施进展</Button> : null}</> : null}{can('maintenance.close') ? <Button onClick={() => open('关闭维护通道', 'maintenance.close', [{ ...noteField, label: '关闭说明', required: admin }])}>关闭维护</Button> : null}</Space></div>
    <Alert type="info" title={d.maintenanceClosedAt ? `维护已关闭 · ${date(d.maintenanceClosedAt)}` : d.maintenanceEndsAt ? `维护截止：${date(d.maintenanceEndsAt)}` : '正式交付后立即开始维护，默认15个自然日'} description="关闭维护不改变用户支付比例，也不会将未解决问题自动标记为解决。" />
    {d.events.filter((event) => event.snapshot.type === 'delivery.publish' || ['DEMO', 'REPAIR'].includes(String(event.snapshot.data.kind))).map((event) => <article className={styles.record} key={event.id}><strong>{event.snapshot.type === 'delivery.publish' ? '正式交付' : kinds[String(event.snapshot.data.kind)]}</strong><p className={styles.prewrap}>{event.snapshot.note}</p>{attachmentLinks(event.snapshot.attachments.map((file) => file.key))}<Space wrap>{Array.isArray(event.snapshot.data.links) ? event.snapshot.data.links.map((url) => <a href={String(url)} key={String(url)} target="_blank" rel="noreferrer">{String(url)}</a>) : null}</Space></article>)}
    <h3>维护问题</h3>{d.issues.length ? d.issues.map((issue) => <article className={styles.record} key={issue.id}><div className={styles['section-heading']}><strong>{issue.title}</strong><Tag>{({ OPEN: '待处理', RESOLVED: '已修复待复测', CLOSED: '已关闭' } as Record<string, string>)[issue.status]}</Tag></div><p>{issue.resolution}</p>{can('issue.update') ? <Button onClick={() => open('补充问题处理记录', 'issue.update', [{ key: 'status', label: '处理状态', type: 'select', required: true, initial: issue.status, options: [{ value: 'OPEN', label: '仍需处理' }, ...(admin ? [{ value: 'RESOLVED', label: '已修复，等待复测' }] : []), { value: 'CLOSED', label: '关闭此问题' }] }, noteField, filesField], { issueId: issue.id })}>记录处理结果</Button> : null}</article>) : <Empty description="当前没有维护问题" />}
  </section>
  const fileTab = <section><div className={styles['section-heading']}><h2>文件与存证</h2><Button href={`${base}/archive`}>下载完整归档</Button></div>{!d.archived ? <CommissionFileUpload base={base} admin={admin} onUploaded={() => void refresh()} /> : null}
    <Table rowKey="id" dataSource={d.files} pagination={false} scroll={{ x: 550 }} columns={[{ title: '文件', render: (_, file) => <a href={`${base}/files/${file.id}`}>{file.name}</a> }, { title: '状态', render: (_, file) => <Tag>{file.submitted ? '已正式提交' : '附件草稿，仅自己可见'}</Tag> }, { title: '大小', dataIndex: 'size', render: (value) => `${(Number(value) / 1024).toFixed(1)} KiB` }, { title: '校验', render: (_, file) => <details><summary>SHA-256</summary><code className={styles.hash}>{file.sha256}</code></details> }]} />
    {admin && !d.archived ? <WorkflowEvidencePanel events={d.events} onUpdated={() => void refresh()} /> : null}
  </section>
  return <div className={styles.workspace}>
    <Link className={styles.back} href={prefix}>返回委托列表</Link><header className={styles.heading}><div><h1>{d.title}</h1><p>{d.subject ? `委托用户：${d.subject}` : '尚未绑定用户，请生成邀请链接，由用户登录认领。'}</p></div><Space wrap><Button onClick={() => void refresh()}>刷新</Button>{primary}</Space></header>
    {query.error ? <Alert type="error" title={query.error.message} /> : null}{d.archived ? <Alert type="info" title="旧流程只读归档，原合同与证据继续保留" /> : null}
    <div className={styles['status-bar']}><div><span>合同生命周期</span><strong>{d.archived ? '历史归档' : WORKFLOW_STAGES[d.stage]}{d.paused ? ' · 暂停' : ''}</strong></div><div><span>用户支付比例</span><strong>{d.paymentPercent}%</strong>{can('payment.update') ? <Button size="small" type="link" onClick={updatePayment}>更新比例</Button> : null}</div><div><span>维护截止时间</span><strong>{d.maintenanceClosedAt ? '已关闭' : d.maintenanceEndsAt ? date(d.maintenanceEndsAt) : '正式交付后开始'}</strong></div></div>
    <div className={styles['detail-grid']}><div className={styles.main}><Tabs activeKey={tab} onChange={setTab} items={[{ key: 'timeline', label: '时间轴', children: timeline }, { key: 'contracts', label: '需求与合同', children: contracts }, { key: 'maintenance', label: '交付与维护', children: maintenance }, { key: 'files', label: '文件与存证', children: fileTab }]} /></div><aside className={styles.sidebar}><h2>当前安排</h2><p>{d.nextAction}</p><Descriptions column={1} size="small" items={[{ key: 'payment', label: '合同金额', children: d.totalFen ? `¥${formatFen(d.totalFen)}` : '尚未约定' }, { key: 'progress', label: '实施进度', children: `${d.progress}%` }, { key: 'duration', label: '维护期限', children: `${d.maintenanceDays} 个自然日` }]} />
      <Space orientation="vertical" className={styles['full-width']}>{can('invitation.create') ? <Button loading={inviteMutation.isPending} onClick={() => inviteMutation.mutate(false)}>生成邀请链接</Button> : null}{can('invitation.revoke') && d.bindingStatus === 'INVITED' ? <Button onClick={() => inviteMutation.mutate(true)}>撤销邀请</Button> : null}{can('draft.update') ? <Button onClick={() => open('编辑委托草稿', 'draft.update', [{ key: 'title', label: '委托名称', required: true, initial: d.title }, { key: 'requirements', label: '需求草稿', type: 'textarea', initial: d.requirements }])}>编辑需求草稿</Button> : null}{can('request.return') ? <Button onClick={() => open('退回补充需求', 'request.return', [noteField])}>退回补充</Button> : null}<Button onClick={() => setTab('files')}>上传附件与查看存证</Button>{can('project.pause') ? <Button onClick={() => open(d.paused ? '恢复项目' : '暂停项目', 'project.pause', [noteField], { paused: !d.paused })}>{d.paused ? '恢复项目' : '暂停项目'}</Button> : null}{can('project.terminate') ? <Button danger onClick={() => open('终止委托', 'project.terminate', [noteField])}>终止委托</Button> : null}<Button href={`${base}/archive`}>下载项目归档</Button></Space>
    </aside></div>
    <ActionDialog spec={dialog} busy={command.isPending} onClose={() => setDialog(null)} onSave={(values) => { const { linksText, ...payload } = values; if (values.action === 'delivery.publish') payload.links = String(linksText || '').split('\n').map((line) => line.trim()).filter(Boolean); if (['payment.update', 'maintenance.close'].includes(String(payload.action))) payload.note ||= ''; command.mutate(payload) }} />
    <WorkflowAgreementEditor key={draft?.commandId || 'closed'} detail={d} spec={draft} busy={command.isPending} onClose={() => setDraft(null)} onSave={(input) => command.mutate(input)} />
    <Drawer title={reading?.title || '合同'} open={Boolean(reading)} onClose={() => setReading(null)} width="min(850px, 100vw)">{reading ? <><Tag>{contractStates[reading.status]}</Tag><section className={styles.paper}><MarkdownView content={reading.body} /></section>{attachmentLinks(reading.fileKeys)}{!admin && reading.status === 'PENDING' && reading.confirmationMode === 'ONLINE' ? <div className={styles.actions}><Button type="primary" disabled={!can('agreement.confirm')} onClick={() => confirm('确认已阅读并同意此合同版本', { action: 'agreement.confirm', id: Number(reading.id), eventId: reading.publishedEventId })}>确认合同</Button><Button disabled={!can('agreement.decline')} onClick={() => open('提出合同异议', 'agreement.decline', [noteField], { id: Number(reading.id), eventId: reading.publishedEventId })}>提出异议</Button></div> : null}</> : null}</Drawer>
    <Modal title="邀请链接已生成" open={Boolean(invite)} onCancel={() => setInvite(null)} footer={<Button onClick={() => setInvite(null)}>完成</Button>}>{invite ? <><p>登录后仅可认领一次，重新生成会使旧链接失效。</p><Input.TextArea readOnly value={`${typeof window === 'undefined' ? '' : window.location.origin}${invite.path}`} rows={3} /><p>有效期至 {date(invite.expiresAt)}</p><Button onClick={() => void navigator.clipboard.writeText(`${window.location.origin}${invite.path}`).then(() => message.success('已复制邀请链接')).catch(() => message.error('复制失败，请手动复制'))}>复制链接</Button></> : null}</Modal>
  </div>
}
