@startuml
skinparam shadowing false
skinparam backgroundColor white
skinparam classBorderColor #334155
skinparam classBackgroundColor #F8FAFC
skinparam defaultFontName Helvetica

class "SystemHomepage" {
  + id: BigInt
  + content: Text
  + status: SmallInt
  + createdAt: DateTime
  + updatedAt: DateTime
  + isDeleted: Boolean
}
@enduml
