@startuml
skinparam shadowing false
skinparam backgroundColor white
skinparam classBorderColor #334155
skinparam classBackgroundColor #F8FAFC
skinparam defaultFontName Helvetica

class "SystemConfig" {
  + id: BigInt
  + configKey: String
  + configValue: String
  + description: String?
  + createdAt: DateTime
  + updatedAt: DateTime
}
@enduml
